---
title: "git_01"
author: "Chi N"
date: "Fall semester"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
# Build a Poem with commits to different branches
Our project will be done using a sequence of save and commits and branch actions.
<!-- Do not modify or change any text in "!--" bracketed areas such as this --- these are instructions to
you, if you change any of this the git program will notice it and compromise your git merging strategy !-->

## First Verse 
<!--Put the first five lines of a poem by Lewis Carrol in this section!-->

## Second Verse
<!--Put the first five lines of a poem by Robert Frost here!-->

## Third Verse
<!--Put the first two verses of The Walrus and the Carpenter here!-->


## Last Verse
<!--Put a short poem you created using chatGPT of 20 to 30 lines,here!-->

In twilight's soft embrace, the day recedes,

As shadows dance in the fading light's domain.

The stars emerge, a celestial decree,

And whispers of the night begin to reign.



Within the silence, secrets start to stir,

Unveiling tales that slumbered in the dark.

Moonbeams cascade, a gentle touch, a lure,

Guiding dreams on their celestial arc.



The earth exhales, a sigh of deep repose,

While dreams take flight on wings of whispered prayer.

In this enchanted realm where time slows,

The heart finds solace in the midnight air.



Through veils of mist, the night reveals its lore,

A tapestry of wonder, rich and vast.

Each constellation, a story to explore,

In this nocturnal symphony, unsurpassed.



The nightingale sings its melancholy tune,

A serenade to solitude's embrace.

And as the velvet sky begins to swoon,

We find our peace in this enchanted space.



So let us wander through this realm of night,

Where dreams take flight and stars illuminate.

In quiet reverence, under Luna's light,

We find our souls in this celestial state.
